### ISSUE TITLE
Dispatch Failure

### ISSUE THREAD

**Issue by Lalalaashen** [automl/Auto-PyTorch#116]
Pyro4.errors.NamingError: Failed to locate the nameserver
TimeoutError

> 11:29:54 [AutoNet] Start bohb
11:29:54 wait_for_workers trying to get the condition
11:29:54 DISPATCHER: started the 'discover_worker' thread
11:29:54 DISPATCHER: started the 'job_runner' thread
11:30:15 No nameserver found. Make sure the nameserver is running at that the host (192.168.x.xx) and port (55780) are correct
Exception in thread worker hpbandster.run_0.worker.DESKTOP-xxxxxxxx.-11104 thread:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\Pyro4\core.py", line 515, in connect_and_handshake
    sslContext=sslContext)
  File "C:\ProgramData\Anaconda3\lib\site-packages\Pyro4\socketutil.py", line 307, in createSocket
    sock.connect(connect)
TimeoutError: [WinError 10060] .......................

**Comment by ravinkohli** [comment]
We have moved to v0.1.0 which is now available in the master branch. It will also be available via `pip install autoPyTorch==0.1.0` in the coming weeks. Please try using that version and feel free to raise an issue if you face any
