### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by AmberLJC** [automl/Auto-PyTorch#13]
Every time  the master will get the following error, while the workers don't  
Anyone knows how to fix it?
Thanks

exception: Traceback (most recent call last):
  File "/users/JIACHEN/.local/lib/python3.6/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/core/worker.py", line 92, in compute
    result = self.optimize_pipeline(config, config_id, budget, start_time)
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/core/worker.py", line 131, in optimize_pipeline
    raise e
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/core/worker.py", line 125, in optimize_pipeline
    refit=False, rescore=False, hyperparameter_config_id=config_id, dataset_info=self.dataset_info)
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/pipeline/base/pipeline.py", line 60, in fit_pipeline
    return self.root.fit_traverse(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/pipeline/base/node.py", line 110, in fit_traverse
    node.fit_output = node.fit(**required_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/pipeline/nodes/cross_validation.py", line 124, in fit
    X=X, Y=Y, logger=logger)
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/pipeline/nodes/cross_validation.py", line 288, in process_additional_results
    combinators[name] = additional_results[split][name]["combinator"]
TypeError: 'int' object is not subscriptable

**Comment by mlindauer** [comment]
Dear @AmberLJC,

Thank you for your interest in AutoPyTorch.
Could you please provide a mini example to reproduce the error?

Best,
Marius

**Comment by AmberLJC** [comment]
Thanks for your reply. I am testing auto-pytorch on multi-workers and master.
(This error only happens on master) I have no idea about this, and the program will continue to run after reporting this error. It happens after every new config  output like:


kwargs: {'config': {'CreateDataLoader:batch_size': 72, 'Imputation:strategy': 'most_frequent', 'InitializationSelector:initialization_method': 'sparse', 'InitializationSelector:initializer:initialize_bias': 'No', 'LearningrateSchedulerSelector:lr_scheduler': 'plateau', 'LossModuleSelector:loss_module': 'cross_entropy', 'NetworkSelector:network': 'shapedresnet', 'NormalizationStrategySelector:normalization_strategy': 'maxabs', 'OptimizerSelector:optimizer': 'sgd', 'PreprocessorSelector:preprocessor': 'truncated_svd', 'ResamplingStrategySelector:over_sampling_method': 'smote', 'ResamplingStrategySelector:target_size_strategy': 'upsample', 'ResamplingStrategySelector:under_sampling_method': 'random', 'TrainNode:batch_loss_computation_technique': 'mixup', 'InitializationSelector:sparse:sparsity': 0.9, 'LearningrateSchedulerSelector:plateau:factor': 0.4556502641981956, 'LearningrateSchedulerSelector:plateau:patience': 8, 'NetworkSelector:shapedresnet:activation': 'tanh', 'NetworkSelector:shapedresnet:blocks_per_group': 1, 'NetworkSelector:shapedresnet:max_units': 44, 'NetworkSelector:shapedresnet:num_groups': 3, 'NetworkSelector:shapedresnet:resnet_shape': 'stairs', 'NetworkSelector:shapedresnet:use_dropout': True, 'NetworkSelector:shapedresnet:use_shake_drop': False, 'NetworkSelector:shapedresnet:use_shake_shake': True, 'OptimizerSelector:sgd:learning_rate': 0.07148684247787404, 'OptimizerSelector:sgd:momentum': 0.1261327153125679, 'OptimizerSelector:sgd:weight_decay': 0.005769455922980964, 'PreprocessorSelector:truncated_svd:target_dim': 215, 'ResamplingStrategySelector:smote:k_neighbors': 3, 'TrainNode:mixup:alpha': 0.9399826926787156, 'NetworkSelector:shapedresnet:dropout_shape': 'brick', 'NetworkSelector:shapedresnet:max_dropout': 0.5504259342674901}, 'budget': 2.4691358024691357, 'working_directory': '.'}
result: None
exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hpbandster-0.7.4-py3.6.egg/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/core/worker.py", line 92, in compute
    result = self.optimize_pipeline(config, config_id, budget, start_time)
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/core/worker.py", line 131, in optimize_pipeline
    raise e
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/core/worker.py", line 125, in optimize_pipeline
    refit=False, rescore=False, hyperparameter_config_id=config_id, dataset_info=self.dataset_info)
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/pipeline/base/pipeline.py", line 60, in fit_pipeline
    return self.root.fit_traverse(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/pipeline/base/node.py", line 110, in fit_traverse
    node.fit_output = node.fit(**required_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/pipeline/nodes/cross_validation.py", line 124, in fit
    X=X, Y=Y, logger=logger)
  File "/usr/local/lib/python3.6/dist-packages/autoPyTorch-0.0.1-py3.6.egg/autoPyTorch/pipeline/nodes/cross_validation.py", line 288, in process_additional_results
    combinators[name] = additional_results[split][name]["combinator"]
TypeError: 'int' object is not subscriptable



Basically, my code is following:



    autonet = AutoNetClassification("medium_cs",
                                    budget_type='epochs', min_budget=1, max_budget=200,
                                    early_stopping_patience=3,
                                    num_iterations=10,
                                    worker_host=args.worker_host,
                                    ns_host=args.ns_host, ns_port=args.ns_port,
                                    min_workers=args.num_worker, task_id=args.task_id,
                                    log_level='debug', use_pynisher=False)

    res = autonet.fit(X_train=dm.X, Y_train=dm.Y,
                      cross_validator="k_fold", cross_validator_args={"n_splits": 3},
                      categorical_features=dm.categorical_features)



BTW may I know in which condition will the program shut down all process.
