### ISSUE TITLE
AttributeError: module 'torch.optim' has no attribute 'AdamW'

### ISSUE THREAD

**Issue by zym604** [automl/Auto-PyTorch#23]
I get the following error saying that torch doesn't have AdamW optimizer.
```
Process pynisher function call:
Traceback (most recent call last):
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/pynisher/limit_function_call.py", line 93, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/core/worker.py", line 124, in optimize_pipeline
    raise e
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/core/worker.py", line 118, in optimize_pipeline
    refit=False, rescore=False, hyperparameter_config_id=config_id, dataset_info=self.dataset_info)
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/pipeline/base/pipeline.py", line 60, in fit_pipeline
    return self.root.fit_traverse(**kwargs)
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/pipeline/base/node.py", line 115, in fit_traverse
    node.fit_output = node.fit(**required_kwargs)
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/pipeline/nodes/cross_validation.py", line 108, in fit
    result = self.sub_pipeline.fit_pipeline(X=X, Y=Y, **sub_pipeline_kwargs)
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/pipeline/base/pipeline.py", line 60, in fit_pipeline
    return self.root.fit_traverse(**kwargs)
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/pipeline/base/node.py", line 115, in fit_traverse
    node.fit_output = node.fit(**required_kwargs)
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/pipeline/nodes/optimizer_selector.py", line 28, in fit
    return {'optimizer': optimizer_type(network.parameters(), optimizer_config)}
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/components/optimizer/optimizer.py", line 22, in __new__
    return cls._get_optimizer(cls, params, config)
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/components/optimizer/optimizer.py", line 51, in _get_optimizer
    return optim.AdamW(params=params, lr=config['learning_rate'], weight_decay=config['weight_decay'])
AttributeError: module 'torch.optim' has no attribute 'AdamW'
20:41:38 job (0, 0, 78) failed with exception
Traceback (most recent call last):
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/yangmo/anaconda2/envs/python3/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/core/worker.py", line 86, in compute
    raise Exception("Exception in train pipeline. Took " + str((time.time()-start_time)) + " seconds with budget " + str(budget))
Exception: Exception in train pipeline. Took 0.11802005767822266 seconds with budget 1.1111111111111112
```
I checked my pytorch 1.1.0, it doesn't have AdamW. Is this a version issue or?
```
>>> optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch.optim' has no attribute 'AdamW'
>>> optimizer = torch.optim.Adamw(model.parameters(), lr=learning_rate)  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch.optim' has no attribute 'Adamw'
>>> optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch.optim' has no attribute 'AdamW'
>>> import torch print(torch.__version__)
  File "<stdin>", line 1
    import torch print(torch.__version__)
                     ^
SyntaxError: invalid syntax
>>> import torch
>>> print(torch.__version__)
1.1.0
>>> 
```

**Comment by LMZimmer** [comment]
Hey,
AdamW was added in PyTorch 1.2.0 so you need that version or higher. We will specify this in the requirements.

**Comment by bimsarapathiraja** [comment]
`nadam = torch.optim.NAdam(model.parameters())`

This gives the same error. My pytorch version is `'1.9.1+cu102'`. VS code does not even suggest the optimzier but the documentation clearly mention the optimizer

**Comment by Riemann1999** [comment]
> 

wrong spelling of Adam

**Comment by vhchuong** [comment]
> > 
> 
> wrong spelling of Adam

Actually [AdamW](https://pytorch.org/docs/stable/generated/torch.optim.AdamW.html#torch.optim.AdamW) is available.
You can take a look.
