### ISSUE TITLE
cannot import name 'ifaddresses' from 'netifaces'

### ISSUE THREAD

**Issue by jcdelpiano** [automl/Auto-PyTorch#288]
Hi all, 

I'm trying to use auto-pytorch and I have this error raised. I do have netifaces v0.10.9 installed, but cannot import 'ifaddresses'. Does anyone else have this problem?

Thank you for your help!

```
cannot import name 'ifaddresses' from 'netifaces' (/home/ubuntu/.cache/Python-Eggs/netifaces-0.10.9-py3.8-linux-x86_64.egg-tmp/netifaces.cpython-38-x86_64-linux-gnu.so)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/autoPyTorch-0.0.2-py3.8.egg/autoPyTorch/pipeline/nodes/optimization_algorithm.py", line 118, in fit
    ns_host, ns_port = NS.start()
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/hpbandster-0.7.4-py3.8.egg/hpbandster/core/nameserver.py", line 62, in start
    self.host = nic_name_to_host(self.nic_name)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/hpbandster-0.7.4-py3.8.egg/hpbandster/core/nameserver.py", line 11, in nic_name_to_host
    from netifaces import ifaddresses, AF_INET
ImportError: cannot import name 'ifaddresses' from 'netifaces' (/home/ubuntu/.cache/Python-Eggs/netifaces-0.10.9-py3.8-linux-x86_64.egg-tmp/netifaces.cpython-38-x86_64-linux-gnu.so)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-80c987ae2dd6> in <module>
      6                             log_level='info')
      7 
----> 8 res = autonet.fit(X_train, 
      9                   y_train,
     10                   validation_split=0.3,

~/anaconda3/lib/python3.8/site-packages/autoPyTorch-0.0.2-py3.8.egg/autoPyTorch/core/api.py in fit(self, X_train, Y_train, X_valid, Y_valid, refit, **autonet_config)
    150 
    151         if "optimized_hyperparameter_config" not in self.fit_result.keys() or not self.fit_result["optimized_hyperparameter_config"]: # MODIFY
--> 152             raise RuntimeError("No models fit during training, please retry with a larger max_runtime.")
    153 
    154         if (refit):

RuntimeError: No models fit during training, please retry with a larger max_runtime.
```

**Comment by ravinkohli** [comment]
I am closing this issue due to inactivity.
