### ISSUE TITLE
KeyError: val_mean_distance

### ISSUE THREAD

**Issue by Vikramardham** [automl/Auto-PyTorch#34]
Dear AutoPyTorch developers,

Thanks a lot for this nice tool. I am trying this out and I seem to encounter an error with the default settings itself. Any help would be greatly appreciated. 

I want to find a decent neural network architecture for an autoencoder (my input and output are the same). Here is the code, I am using, 
```

apt = AutoNetRegression(config_preset='medium_cs',
                        log_level='info',
                        networks=['mlpnet'],
                        use_pynisher=False,
                        cuda=True,
                        use_tensorboard_logger=True,
                        best_over_epochs=True,
                        algorithm='hyperband',
                        budget_type='epochs',
                                    max_runtime=10,
                                    min_budget=1,
                                    max_budget=90,
                        #optimize_metric = accuracy,
                    #loss_modules =['l1_loss'],
                       early_stopping_patience=10,
                       early_stopping_reset_parameters=True,
                       ) 
apt.fit(x_train_transform, x_train_transform, validation_split= 0.3)
```
My input data 'x_train_transform' is a numpy array with shape (100000, 12) and dtype float. When I run the above code, I encounter the following error within the first few seconds. It seems to arise from the 'optimize_metric' option, however I cannot choose any value other than 'mean_distance'. (max_run_time has no influence on this problem)

```
17:42:36 WORKER: start listening for jobs
17:42:36 [AutoNet] Start hyperband
17:42:36 DISPATCHER: started the 'discover_worker' thread
17:42:36 DISPATCHER: started the 'job_runner' thread
17:42:36 DISPATCHER: Pyro daemon running on 134.21.15.194:38097
17:42:36 DISPATCHER: discovered new worker, hpbandster.run_0.worker.biolpc81.21492.-1140535582213952
17:42:36 HBMASTER: adjusted queue size to (0, 1)
17:42:36 DISPATCHER: A new worker triggered discover_worker
17:42:36 HBMASTER: starting run at 1582130556.8857265
17:42:36 WORKER: start processing job (0, 0, 0)
17:42:36 Fit optimization pipeline
17:42:37 [AutoNet] No validation set given and either no cross validator given or budget too low for CV. Continue by splitting 0.3 of training data.
17:42:37 [AutoNet] CV split 0 of 1

The Box-Cox transformation can only be applied to strictly positive data
Using yeo-johnson instead

17:43:14 'val_mean_distance'
17:43:14 WORKER: registered result for job (0, 0, 0) with dispatcher
17:43:14 job (0, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/core/worker.py", line 88, in compute
    result = self.optimize_pipeline(config, config_id, budget, start_time)
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/core/worker.py", line 124, in optimize_pipeline
    raise e
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/core/worker.py", line 118, in optimize_pipeline
    refit=False, rescore=False, hyperparameter_config_id=config_id, dataset_info=self.dataset_info)
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/pipeline/base/pipeline.py", line 60, in fit_pipeline
    return self.root.fit_traverse(**kwargs)
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/pipeline/base/node.py", line 115, in fit_traverse
    node.fit_output = node.fit(**required_kwargs)
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/pipeline/nodes/cross_validation.py", line 108, in fit
    result = self.sub_pipeline.fit_pipeline(X=X, Y=Y, **sub_pipeline_kwargs)
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/pipeline/base/pipeline.py", line 60, in fit_pipeline
    return self.root.fit_traverse(**kwargs)
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/pipeline/base/node.py", line 115, in fit_traverse
    node.fit_output = node.fit(**required_kwargs)
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/pipeline/nodes/train_node.py", line 132, in fit
    best_over_epochs=pipeline_config['best_over_epochs'], refit=refit, logger=logger)
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/pipeline/nodes/train_node.py", line 249, in wrap_up_training
    logs=logs, train_loader=train_loader, valid_loader=valid_loader, best_over_epochs=best_over_epochs, refit=refit)
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/components/training/trainer.py", line 72, in final_eval
    final_log = min(logs, key=lambda log: self.metrics[0].loss_transform(log[opt_metric_name]))
  File "/home/vikrama/anaconda3/envs/fastai/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/components/training/trainer.py", line 72, in <lambda>
    final_log = min(logs, key=lambda log: self.metrics[0].loss_transform(log[opt_metric_name]))
KeyError: 'val_mean_distance'

17:43:14 HBMASTER: Timelimit reached: wait for remaining 0 jobs
17:43:14 DISPATCHER: Dispatcher shutting down
17:43:14 DISPATCHER: shut down complete

Error parsing results. Check results.json and output for more details. An empty results.json is usually caused by a misconfiguration of AutoNet.
```

Am I missing something?

Thanks a lot, in advance.

**Comment by LMZimmer** [comment]
Hey,

could you perhaps try if the error also occurs when using `full_cs` as config preset and/or increase the `max_runtime`? There may be an issue because the mlpnet is not in the medium preset or because there is no model fully fitted.

**Comment by Vikramardham** [comment]
Hi LMZimmer,

Thanks a lot for your quick response.

I tried 'full_cs' configuration to no avail. I had already tested changing max_runtime (by two orders of magnitude), no luck there too.

**Comment by LMZimmer** [comment]
In that case maybe try setting `full_eval_each_epoch=True`. My suspicion is that there is no full evaluation for the max runtime you specify.

**Comment by Vikramardham** [comment]
Thanks a lot. This setting runs without an error.
What exactly is happening here?

**Comment by LMZimmer** [comment]
It looks like the an issue when `best_over_epochs` is set to True (meaning that the best performance over the training is considered and no the final log) and `full_eval_each_epoch` is set to false. Then, when looking for the best performance in the [trainer](https://github.com/automl/Auto-PyTorch/blob/b76a9025bd2e2937d094091409c15104bb440743/autoPyTorch/components/training/trainer.py#L69), the logs do not contain the logs on the validation set. One possible solution might be setting other defaults at the cost of transparency.
