### ISSUE TITLE
in windows, ModuleNotFoundError: No module named 'resource'?

### ISSUE THREAD

**Issue by Dian-Yi** [automl/Auto-PyTorch#385]
i run demo [https://automl.github.io/Auto-PyTorch/master/examples/20_basics/example_tabular_classification.html#sphx-glr-examples-20-basics-example-tabular-classification-py](url) and meet error.
this error is caused by pynisher, maybe my system is windows. 
Have you encountered or solved this problem?
EROOR Message:
Traceback (most recent call last):
 File "D:/project/train_autoML.py", line 23, in <module>
    from autoPyTorch.api.tabular_classification import TabularClassificationTask
  File "C:\Users\anaconda3\envs\emotion\lib\site-packages\autoPyTorch\api\tabular_classification.py", line 9, in <module>
    from autoPyTorch.api.base_task import BaseTask
  File "C:\Users\anaconda3\envs\emotion\lib\site-packages\autoPyTorch\api\base_task.py", line 42, in <module>
    from autoPyTorch.ensemble.ensemble_builder import EnsembleBuilderManager
  File "C:\Users\anaconda3\envs\emotion\lib\site-packages\autoPyTorch\ensemble\ensemble_builder.py", line 24, in <module>
    import pynisher
  File "C:\Users\anaconda3\envs\emotion\lib\site-packages\pynisher\__init__.py", line 1, in <module>
    from pynisher.limit_function_call import * # noqa
  File "C:\Users\anaconda3\envs\emotion\lib\site-packages\pynisher\limit_function_call.py", line 2, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

**Comment by ravinkohli** [comment]
Could you provide more details about your environment? for example the `pip freeze`.

**Comment by fyq163** [comment]
Have you fixed it yet? It looks like the resource mod refers to that resource of Linux?

**Comment by Dian-Yi** [comment]
> Have you fixed it yet? It looks like the resource mod refers to that resource of Linux?

no, you maybe run this on linux.

**Comment by aghaphd** [comment]
Hello, I'm facing same problem says import resource
ModuleNotFoundError: No module named 'resource'
My system is Windows, and using pytorch 1.01. How to solve it?

**Comment by aghaphd** [comment]
Solved, I commented it out #.
