### ISSUE TITLE
ValueError: Active hyperparameter 'network_backbone:seq_encoder:block_1:MLPDecoder:auto_regressive' not specified!

### ISSUE THREAD

**Issue by Yuang-Deng** [automl/Auto-PyTorch#460]
NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://stackoverflow.com

Your issue may already be reported!
Also, please search on the [issue tracker](../) before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

# Issue Description
* When Issue Happens
* Steps To Reproduce
  1.ConfigSpace from https://github.com/dengdifan/ConfigSpace.git
  1.Auto-Pytorch from git@github.com:dengdifan/Auto-PyTorch.git
  1.run ./examples/APT-TS/APT_task.py

## Expected Behavior

What causes this problem and how to fix it

## Your Code

```python
import numpy as np

from autoPyTorch.api.time_series_forecasting import TimeSeriesForecastingTask
import pandas as pds
from datetime import datetime
import warnings
import os
import copy
from pathlib import Path

import argparse

import csv
import shutil

from autoPyTorch.datasets.resampling_strategy import (
    CrossValTypes,
    HoldoutValTypes,
)

import data_loader
from constant import VALUE_COL_NAME, TIME_COL_NAME, SEASONALITY_MAP, FREQUENCY_MAP, DATASETS


def compute_loss(forecast_horizon, seasonality, final_forecasts, test_series_list, train_series_list):
    epsilon = 0.1

    MASE = []
    sMAPE = []
    msMAPE = []
    MAE = []
    RMSE = []

    sqrt_forecast_horizon = np.sqrt(forecast_horizon)

    idx = 0

    for f, y, y_data in zip(final_forecasts, test_series_list, train_series_list):

        M = len(y_data)

        diff_abs = np.abs(f - y)

        if M == seasonality:
            mase_denominator = 0
        else:
            mase_denominator_coefficient = forecast_horizon / (M - seasonality)
            mase_denominator = mase_denominator_coefficient * \
                               np.sum(np.abs(y_data[seasonality:] - y_data[:-seasonality]))

            abs_loss = np.sum(diff_abs)
            mase = abs_loss / mase_denominator

        if mase_denominator == 0:
            mase_denominator_coefficient = forecast_horizon / (M - 1)
            mase_denominator = mase_denominator_coefficient * \
                               np.sum(np.abs(y_data[1:] - y_data[:-1]))
            mase = abs_loss / mase_denominator

        if np.isnan(mase) or np.isinf(mase):
            # see the R file
            pass
        else:
            MASE.append(mase)

        smape = 2 * diff_abs / (np.abs(y) + np.abs(f))
        smape[diff_abs == 0] = 0
        smape = np.sum(smape) / forecast_horizon
        sMAPE.append(smape)

        msmape = np.sum(2 * diff_abs / (np.maximum(np.abs(y) + np.abs(f) + epsilon, epsilon + 0.5))) / forecast_horizon
        msMAPE.append(msmape)

        mae = abs_loss / forecast_horizon
        MAE.append(mae)

        rmse = np.linalg.norm(f - y) / sqrt_forecast_horizon
        RMSE.append(rmse)


        idx += 1
    res = {}

    res['Mean MASE'] = np.mean(MASE)

    res['Median MASE'] = np.median(MASE)

    res['Mean sMAPE'] = np.mean(sMAPE)
    res['Median sMAPE'] = np.median(sMAPE)

    res['Mean mSMAPE'] = np.mean(msMAPE)
    res['Median mSMAPE'] = np.median(msMAPE)

    res['Mean MAE'] = np.mean(MAE)
    res['Median MAE'] = np.median(MAE)

    res['Mean RMSE'] = np.mean(RMSE)
    res['Median RMSE'] = np.median(RMSE)


    return res


def main(working_dir="/home/$USER/tmp/tmp",
         dataset_name='nn5_daily',
         budget_type='dataset_size',
         res_dir="./APT_run",
         validation='holdout',
         seed=1):
    file_name, external_forecast_horizon, integer_conversion = DATASETS[dataset_name]

    dataset_path = Path(working_dir) / "tsf_data" / dataset_name / file_name

    df, frequency, forecast_horizon, contain_missing_values, contain_equal_length = \
        data_loader.convert_tsf_to_dataframe(str(dataset_path))

    # If the forecast horizon is not given within the .tsf file, then it should be provided as a function input
    if forecast_horizon is None:
        if external_forecast_horizon is None:
            raise Exception("Please provide the required prediction steps")
        else:
            forecast_horizon = external_forecast_horizon

    train_series_list = []
    test_series_list = []

    X_train = []
    y_train = []

    X_test = []
    y_test = []

    if frequency is not None:
        freq = FREQUENCY_MAP[frequency]
        seasonality = SEASONALITY_MAP[frequency]
    else:
        freq = "1Y"
        seasonality = 1

    shortest_sequence = np.inf
    train_start_time_list = []

    for index, row in df.iterrows():
        if TIME_COL_NAME in df.columns:
            train_start_time = row[TIME_COL_NAME]
        else:
            train_start_time = datetime.strptime('1900-01-01 00-00-00',
                                                 '%Y-%m-%d %H-%M-%S')  # Adding a dummy timestamp, if the timestamps are not available in the dataset or consider_time is False
        train_start_time_list.append(pds.Timestamp(train_start_time, freq=freq))

        series_data = row[VALUE_COL_NAME].to_numpy()
        # Creating training and test series. Test series will be only used during evaluation
        train_series_data = series_data[:len(series_data) - forecast_horizon]
        test_series_data = series_data[(len(series_data) - forecast_horizon): len(series_data)]

        y_test.append(series_data[-forecast_horizon:])

        train_series_list.append(train_series_data)
        test_series_list.append(test_series_data)

        shortest_sequence = min(len(train_series_data), shortest_sequence)

    if validation == 'cv':
        n_splits = 3
        while shortest_sequence - forecast_horizon - forecast_horizon * n_splits <= 0:
            n_splits -= 1

        if n_splits >= 2:
            resampling_strategy = CrossValTypes.time_series_cross_validation
            resampling_strategy_args = {'num_splits': n_splits}

        else:
            warnings.warn('The dataset is not suitable for cross validation, we will try holdout instead')
            validation = 'holdout'
    elif validation == 'holdout_ts':
        resampling_strategy = CrossValTypes.time_series_ts_cross_validation
        resampling_strategy_args = None
    if validation == 'holdout':
        resampling_strategy = HoldoutValTypes.time_series_hold_out_validation
        resampling_strategy_args = None


    X_train = copy.deepcopy(train_series_list)
    y_train = copy.deepcopy(train_series_list)

    X_test = copy.deepcopy(X_train)

    path = Path(working_dir) / 'APT_run'
    path_log = str(path / dataset_name / budget_type / f'{seed}' / "log")
    path_pred = str(path / dataset_name / budget_type / f'{seed}' / "output")

    # Remove intermediate files
    try:
        shutil.rmtree(path_log)
        shutil.rmtree(path_pred)
    except OSError as e:
        print("Error: %s - %s." % (e.filename, e.strerror))

    smac_source_dir = Path(path_log) / "smac3-output"


    api = TimeSeriesForecastingTask(
        #delete_tmp_folder_after_terminate=False,
        #delete_output_folder_after_terminate=False,
        seed=seed,
        ensemble_size=20,
        resampling_strategy=resampling_strategy,
        resampling_strategy_args=resampling_strategy_args,
        temporary_directory=path_log,
        output_directory=path_pred,
    )

    api.set_pipeline_config(device="cuda",
                            torch_num_threads=8,
                            early_stopping=20)
    if budget_type == "random_search":
        budget_kwargs = {'budget_type': 'random_search',
                         'max_budget': None,
                         'min_budget': None}

    elif budget_type != 'full_budget':
        from autoPyTorch.constants_forecasting import FORECASTING_BUDGET_TYPE
        if budget_type not in FORECASTING_BUDGET_TYPE and budget_type != 'epochs':
            raise NotImplementedError('Unknown Budget Type!')
        budget_kwargs = {'budget_type': budget_type,
                         'max_budget': 50 if budget_type == 'epochs' else 1.0,
                         'min_budget': 5 if budget_type == 'epochs' else 0.1}
    else:
        budget_kwargs = {'budget_type': 'epochs',
                         'max_budget': 50,
                         'min_budget': 50}

    api.search(
        X_train=None,
        y_train=copy.deepcopy(y_train),
        optimize_metric='mean_MASE_forecasting',
        n_prediction_steps=forecast_horizon,
        **budget_kwargs,
        freq=freq,
        start_times_train=train_start_time_list,
        memory_limit=32 * 1024,
        normalize_y=False,
        total_walltime_limit=600,
        min_num_test_instances=1000,
    )

    from autoPyTorch.data.time_series_forecasting_validator import TimeSeriesForecastingInputValidator

    res_dir = Path(res_dir)

    res_dir_task = res_dir / dataset_name / budget_type / f'{seed}'

    smac_res_path = res_dir_task / 'smac3-output'

    if not os.path.exists(str(res_dir_task)):
        os.makedirs(str(res_dir_task))

    try:
        shutil.rmtree(smac_res_path)
    except OSError as e:
        print("Error: %s - %s." % (e.filename, e.strerror))

    try:
        shutil.copytree(str(smac_source_dir), smac_res_path)
    except OSError as e:  # python >2.5
        print("Error: %s - %s." % (e.filename, e.strerror))


    refit_dataset = api.dataset.create_refit_set()

    train_pred_seq = []
    test_sets = api.dataset.generate_test_seqs()

    try:
        api.refit(refit_dataset, 0)

        pred = api.predict(test_sets)

    except Exception as e:
        print(e)
        exit()


    if integer_conversion:
        final_forecasts = np.round(pred)
    else:
        final_forecasts = pred

    if frequency is not None:
        freq = FREQUENCY_MAP[frequency]
        seasonality = SEASONALITY_MAP[frequency]
    else:
        freq = "1Y"
        seasonality = 1

    if isinstance(seasonality, list):
        seasonality = min(seasonality)  # Use to calculate MASE
    seasonality = int(seasonality)

    res = compute_loss(forecast_horizon, seasonality, final_forecasts, y_test, train_series_list)
    print(res)


    # write the forecasting results to a file
    forecast_file_path = res_dir_task / f"{dataset_name}_{budget_type}_results.txt"

    with open(forecast_file_path, "w") as output:
        writer = csv.writer(output, lineterminator='\n')
        writer.writerows(final_forecasts)

    # Write training dataset and the actual results into separate files, which are then used for error calculations
    # We do not use the built-in evaluation method in GluonTS as some of the error measures we use are not implemented in that
    temp_dataset_path = res_dir_task / f"{dataset_name}_dataset.txt"
    temp_results_path = res_dir_task / f"{dataset_name}_ground_truth.txt"

    # with open(str(temp_dataset_path), "w") as output_dataset:
    #    writer = csv.writer(output_dataset, lineterminator='\n')
    #    writer.writerows(train_series_list)

    with open(str(temp_results_path), "w") as output_results:
        writer = csv.writer(output_results, lineterminator='\n')
        writer.writerows(test_series_list)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='APT_Task')
    parser.add_argument('--dataset_name', type=str, default="m3_yearly", help='dataset name')
    parser.add_argument("--budget_type", default="epochs", type=str, help='budget type')
    parser.add_argument("--working_dir", default="/home/ubuntu/tsbench", type=str,
                        help="directory where datasets and tmp files are stored")
    parser.add_argument('--validation', type=str, default="holdout", help='type of validation')
    parser.add_argument('--seed', type=int, default="10", help='random seed')

    args = parser.parse_args()

    dataset_name = args.dataset_name
    budget_type = args.budget_type
    working_dir = args.working_dir
    validation = args.validation
    seed = args.seed

    main(working_dir=working_dir, dataset_name=dataset_name, budget_type=budget_type, validation=validation, seed=seed)
```

## Error message

```bash
/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (SMAPE). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_full_state_property`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.
                
  warnings.warn(*args, **kwargs)
./examples/APT-TS/APT_task.py:149: FutureWarning: The 'freq' argument in Timestamp is deprecated and will be removed in a future version.
  train_start_time_list.append(pds.Timestamp(train_start_time, freq=freq))
Error: /home/ubuntu/autopytorch/Auto-PyTorch/work_dirs/APT_run/m3_yearly/epochs/10/log - No such file or directory.
[WARNING] [2022-08-05 03:08:58,176:Client-AutoPyTorch:ed2c3260-146b-11ed-ab8d-6d7b46992de8:10] Time limit for a single run is higher than total time limit. Capping the limit for a single run to the total time given to SMAC (35997.000000)
[WARNING] [2022-08-05 03:08:58,176:Client-AutoPyTorch:ed2c3260-146b-11ed-ab8d-6d7b46992de8:10] Capping the func_eval_time_limit_secs to 17998 to have time for a least 2 models to ensemble.
/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/intensification/parallel_scheduling.py:149: UserWarning: Hyperband is intended to be used with more than 1 worker but num_workers=1
  warnings.warn("{} is intended to be used "
        [ERROR] [2022-08-05 03:19:34,585:Client-AutoPyTorch:ed2c3260-146b-11ed-ab8d-6d7b46992de8:10] Active hyperparameter 'network_backbone:seq_encoder:block_1:MLPDecoder:auto_regressive' not specified!
Traceback (most recent call last):
  File "/home/ubuntu/autopytorch/Auto-PyTorch/autoPyTorch/api/base_task.py", line 1106, in _search
    _proc_smac.run_smbo(func=tae_func)
  File "/home/ubuntu/autopytorch/Auto-PyTorch/autoPyTorch/optimizer/smbo.py", line 474, in run_smbo
    smac.optimize()
  File "/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/facade/smac_ac_facade.py", line 597, in optimize
    incumbent = self.solver.run()
  File "/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/optimizer/smbo.py", line 213, in run
    intent, run_info = self.intensifier.get_next_run(
  File "/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/intensification/parallel_scheduling.py", line 165, in get_next_run
    intent, run_info = self.intensifier_instances[i].get_next_run(
  File "/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/intensification/hyperband.py", line 230, in get_next_run
    intent, run_info = self.sh_intensifier.get_next_run(
  File "/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/intensification/successive_halving.py", line 540, in get_next_run
    challenger = self._next_challenger(challengers=challengers,
  File "/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/intensification/abstract_racer.py", line 255, in _next_challenger
    for challenger in chall_gen:
  File "/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/optimizer/ei_optimization.py", line 710, in __next__
    self.challengers = self.challengers_callback()
  File "/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/optimizer/ei_optimization.py", line 92, in next_configs_by_acq_value
    return [t[1] for t in self._maximize(runhistory, stats, num_points)]
  File "/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/optimizer/ei_optimization.py", line 643, in _maximize
    next_configs_by_local_search = self.local_search._maximize(
  File "/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/optimizer/ei_optimization.py", line 233, in _maximize
    configs_acq = self._do_search(init_points)
  File "/home/ubuntu/autopytorch/Auto-PyTorch/.venv/lib/python3.8/site-packages/smac/optimizer/ei_optimization.py", line 367, in _do_search
    n = next(neighborhood_iterator)
  File "ConfigSpace/util.pyx", line 219, in get_one_exchange_neighbourhood
  File "ConfigSpace/configuration_space.pyx", line 1495, in ConfigSpace.configuration_space.Configuration.is_valid_configuration
  File "ConfigSpace/c_util.pyx", line 38, in ConfigSpace.c_util.check_configuration
  File "ConfigSpace/c_util.pyx", line 103, in ConfigSpace.c_util.check_configuration
ValueError: Active hyperparameter 'network_backbone:seq_encoder:block_1:MLPDecoder:auto_regressive' not specified!
```

## Your Local environment
* Operating System, version
* *20.04.1-Ubuntu
* Python, version
* *3.8.10
* Outputs of `pip freeze` or `conda list`
```bash
absl-py==1.2.0
aiohttp==3.8.1
aiosignal==1.2.0
alembic==1.8.1
async-timeout==4.0.2
attrs==22.1.0
autopage==0.5.1
-e git+git@github.com:dengdifan/Auto-PyTorch.git@1b46d88885ea6e7e1b98a0379fcef58e14285b25#egg=autoPyTorch
cachetools==5.2.0
catboost==1.0.6
certifi==2022.6.15
charset-normalizer==2.1.0
click==8.1.3
cliff==3.10.1
cloudpickle==2.1.0
cmaes==0.8.2
cmd2==2.4.2
colorlog==6.6.0
-e git+https://github.com/dengdifan/ConfigSpace.git@4d69931de5540fc6be4230731ddebf6a25d2e1a8#egg=ConfigSpace
convertdate==2.4.0
cycler==0.11.0
Cython==0.29.32
dask==2022.7.1
Deprecated==1.2.13
distributed==2022.7.1
flaky==3.7.0
fonttools==4.34.4
frozenlist==1.3.1
fsspec==2022.7.1
gluonts==0.10.2
google-auth==2.9.1
google-auth-oauthlib==0.4.6
graphviz==0.20.1
greenlet==1.1.2
grpcio==1.47.0
HeapDict==1.0.1
hijri-converter==2.2.4
holidays==0.14.2
idna==3.3
imageio==2.21.0
imgaug==0.4.0
importlib-metadata==4.12.0
importlib-resources==5.9.0
Jinja2==3.1.2
joblib==1.1.0
kiwisolver==1.4.4
korean-lunar-calendar==0.2.1
lightgbm==3.3.2
llvmlite==0.39.0
locket==1.0.0
lockfile==0.12.2
Mako==1.2.1
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.5.2
msgpack==1.0.4
multidict==6.0.2
networkx==2.8.5
numba==0.56.0
numpy==1.22.4
oauthlib==3.2.0
opencv-python==4.6.0.66
optuna==2.10.1
packaging==21.3
pandas==1.4.3
partd==1.2.0
patsy==0.5.2
pbr==5.9.0
Pillow==9.2.0
plotly==5.9.0
prettytable==3.3.0
protobuf==3.19.4
psutil==5.9.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.9.1
pyDeprecate==0.3.2
PyMeeus==0.5.11
pynisher==0.6.4
pyparsing==3.0.9
pyperclip==1.8.2
pyrfr==0.8.3
python-dateutil==2.8.2
pytorch-forecasting==0.10.2
pytorch-lightning==1.7.0
pytz==2022.1
PyWavelets==1.3.0
PyYAML==6.0
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
scikit-image==0.19.3
scikit-learn==0.24.2
scipy==1.8.1
Shapely==1.8.2
six==1.16.0
sktime==0.13.0
smac==0.14.0
sortedcontainers==2.4.0
SQLAlchemy==1.4.39
statsmodels==0.13.2
stevedore==4.0.0
tabulate==0.8.10
tblib==1.7.0
tenacity==8.0.1
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
threadpoolctl==3.1.0
tifffile==2022.8.3
toolz==0.12.0
torch==1.12.0
torchmetrics==0.9.3
torchvision==0.13.0
tornado==6.1
tqdm==4.64.0
typing-extensions==4.3.0
urllib3==1.26.11
wcwidth==0.2.5
Werkzeug==2.2.1
wrapt==1.14.1
yarl==1.8.1
zict==2.2.0
zipp==3.8.1
```

Make sure to add **all the information needed to understand the bug** so that someone can help. 
If the info is missing, we'll add the 'Needs more information' label and close the issue until there is enough information.

**Comment by Yuang-Deng** [comment]
@dengdifan Hi, I got the above error when running the time series forecasting task, can you please help me to solve this problem.

**Comment by dengdifan** [comment]
Hi, 

did you install ConfigSpace from the https://github.com/dengdifan/ConfigSpace/tree/diamond_cond branch or master branch? This issue might come from a bug in ConfigSpace and this update is already merged into https://github.com/automl/ConfigSpace
Could you please install ConfigSpace from that repo and try the above code again? 
FYI. APT for TimeSeries Forecasting is already integrated into the main branch. You could also try the codes here with several minor changes.

Best regards,
DIfan

**Comment by Yuang-Deng** [comment]
Thanks for your reply, I have installed and run successfully with the latest repo.
