### ISSUE TITLE
Error in using command "from autoPyTorch.api.time_series_forecasting import TimeSeriesForecastingTask"

### ISSUE THREAD

**Issue by alirostami9972** [automl/Auto-PyTorch#499]
I'm using Auto-PyTorch to do time series forecasting and employing in google colab and also in IDLE. In google colab, I encountered this error:

OSError                                   Traceback (most recent call last)
<ipython-input-6-42f75d149860> in <cell line: 1>()
----> 1 from autoPyTorch.api.time_series_forecasting import TimeSeriesForecastingTask

39 frames
/usr/lib/python3.10/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    372 
    373         if handle is None:
--> 374             self._handle = _dlopen(self._name, mode)
    375         else:
    376             self._handle = handle

OSError: /usr/local/lib/python3.10/dist-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

And also, using and eploying in IDLE, I encoutered this error:

Traceback (most recent call last):
  File "C:\Users\rosta\OneDrive\Desktop\Auto-PyTorch.py", line 5, in <module>
    from autoPyTorch.api.time_series_forecasting import TimeSeriesForecastingTask
  File "C:\Users\rosta\AppData\Roaming\Python\Python37\site-packages\autoPyTorch\api\time_series_forecasting.py", line 7, in <module>
    from autoPyTorch.api.base_task import BaseTask
  File "C:\Users\rosta\AppData\Roaming\Python\Python37\site-packages\autoPyTorch\api\base_task.py", line 53, in <module>
    from autoPyTorch.ensemble.ensemble_builder import EnsembleBuilderManager
  File "C:\Users\rosta\AppData\Roaming\Python\Python37\site-packages\autoPyTorch\ensemble\ensemble_builder.py", line 24, in <module>
    import pynisher
  File "C:\Users\rosta\AppData\Roaming\Python\Python37\site-packages\pynisher\__init__.py", line 1, in <module>
    from pynisher.limit_function_call import * # noqa
  File "C:\Users\rosta\AppData\Roaming\Python\Python37\site-packages\pynisher\limit_function_call.py", line 2, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

Is there anyone to help me? I don't really know how to solve it?

**Comment by dengdifan** [comment]
Hi, 
that looks like a dependency issue: did you check the solutions here https://github.com/pytorch/audio/issues/2532 and here: https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource

**Comment by alirostami9972** [comment]
> Hi, that looks like a dependency issue: did you check the solutions here [pytorch/audio#2532](https://github.com/pytorch/audio/issues/2532) and here: https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource



Yes, I did it the steps which was mentioned in this link: "https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource",but it doesn't work me.
