### ISSUE TITLE
Errors on running example_tabular_classification.py

### ISSUE THREAD

**Issue by lyz-sys** [automl/Auto-PyTorch#503]
when I run `python examples/20_basics/example_tabular_classification.py`, the terminal shows 

```
Traceback (most recent call last):
  File "examples/20_basics/example_tabular_classification.py", line 26, in <module>
    from autoPyTorch.api.tabular_classification import TabularClassificationTask
  File "/opt/homebrew/anaconda3/envs/auto-pytorch/lib/python3.8/site-packages/autoPyTorch-0.2.1-py3.8.egg/autoPyTorch/api/tabular_classification.py", line 7, in <module>
    from autoPyTorch.api.base_task import BaseTask
  File "/opt/homebrew/anaconda3/envs/auto-pytorch/lib/python3.8/site-packages/autoPyTorch-0.2.1-py3.8.egg/autoPyTorch/api/base_task.py", line 20, in <module>
    import dask.distributed
  File "/opt/homebrew/anaconda3/envs/auto-pytorch/lib/python3.8/site-packages/dask/distributed.py", line 11, in <module>
    from distributed import *
  File "/opt/homebrew/anaconda3/envs/auto-pytorch/lib/python3.8/site-packages/distributed-2023.8.1-py3.8.egg/distributed/__init__.py", line 23, in <module>
    from distributed.actor import Actor, ActorFuture, BaseActorFuture
  File "/opt/homebrew/anaconda3/envs/auto-pytorch/lib/python3.8/site-packages/distributed-2023.8.1-py3.8.egg/distributed/actor.py", line 13, in <module>
    from distributed.client import Future
  File "/opt/homebrew/anaconda3/envs/auto-pytorch/lib/python3.8/site-packages/distributed-2023.8.1-py3.8.egg/distributed/client.py", line 61, in <module>
    from distributed import cluster_dump, preloading
  File "/opt/homebrew/anaconda3/envs/auto-pytorch/lib/python3.8/site-packages/distributed-2023.8.1-py3.8.egg/distributed/preloading.py", line 225, in <module>
    class PreloadManager(Sequence[Preload]):
TypeError: 'ABCMeta' object is not subscriptable
```

I did manual installation by running the following commands
```
# Following commands assume the user is in a cloned directory of Auto-Pytorch

# We also need to initialize the automl_common repository as follows
# You can find more information about this here:
# https://github.com/automl/automl_common/
git submodule update --init --recursive

# Create the environment
conda create -n auto-pytorch python=3.8
conda activate auto-pytorch
conda install swig
python setup.py install
```

Is this error somehow related to the version of auto-pytorch or distributed? How do you think I should solve it?

**Comment by aniketsharma00411** [comment]
It worked when I installed it using the pip command on a 3.8 version environment.
