### ISSUE TITLE
meet TypeError when use AutoNetImageClassification

### ISSUE THREAD

**Issue by Dosomecrazy** [automl/Auto-PyTorch#57]
hi, i follow Auto-PyTorch Tutorial.ipynb and use AutoNetImageClassification, but meet TypeError error like this:

`job (0, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/root/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/root/anaconda3/lib/python3.7/site-packages/autoPyTorch-0.0.2-py3.7.egg/autoPyTorch/core/worker_no_timelimit.py", line 60, in compute
    result, randomstate = limit_train(config, budget, config_id, random.getstate())
TypeError: cannot unpack non-iterable NoneType object`

Thanks for your fantastic work! Looking forward to hearing from you!

**Comment by LMZimmer** [comment]
Hey there, glad to hear that you are enjoying our work. The newest commit should fix this issue. If not feel free to reopen the issue.
