### ISSUE TITLE
Image classification code example not working

### ISSUE THREAD

**Issue by mehravehs** [automl/Auto-PyTorch#60]
When running the `AutoNetImageClassification` according to the example [Auto-PyTorch Tutorial](https://github.com/automl/Auto-PyTorch/blob/master/examples/basics/Auto-PyTorch%20Tutorial.ipynb) notebook, I get the following error:

```
Process pynisher function call:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pynisher/limit_function_call.py", line 93, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/autoPyTorch-0.0.2-py3.6.egg/autoPyTorch/core/worker_no_timelimit.py", line 108, in optimize_pipeline
    random.setstate(random_state)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/random.py", line 134, in setstate
    version = state[0]
TypeError: 'float' object is not subscriptable
02:30:09 job (0, 0, 0) failed with exception
Traceback (most recent call last):
```

**Comment by LMZimmer** [comment]
Hey there, I believe this bug was already addressed in a recent commit. Could you pull from GitHub and see if that works?

**Comment by LMZimmer** [comment]
Fixed with the newest commit
