### ISSUE TITLE
MNIST

### ISSUE THREAD

**Issue by mens-artis** [automl/Auto-PyTorch#77]
On Colab. I basically just replace the CIFAR example in the basic examples notebook with MNIST, having added an MNIST CSV (MNIST, 0) file. If I understand correctly, something like this is supposed to work out of the box: the image tensor shape is/should be auto detected.

"""
path_to_mnist_csv = os.path.abspath("/content/drive/MyDrive/Auto-PyTorch-master/datasets/MNIST.csv")

autonet_image_classification.fit(X_train=np.array([path_to_mnist_csv]),
                                 Y_train=np.array([0]),
                                 min_budget=200,
                                 max_budget=400,
                                 max_runtime=1600,
                                 default_dataset_download_dir="/content/drive/MyDrive/Auto-PyTorch-master/datasets",
                                 images_root_folders=["/content/drive/MyDrive/Auto-PyTorch-master/datasets"])
"""

0 60000
Process pynisher function call:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pynisher/limit_function_call.py", line 133, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/core/worker_no_timelimit.py", line 125, in optimize_pipeline
    raise e
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/core/worker_no_timelimit.py", line 119, in optimize_pipeline
    config_id=config_id, working_directory=self.working_directory), random.getstate()
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/pipeline/base/pipeline.py", line 60, in fit_pipeline
    return self.root.fit_traverse(**kwargs)
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/pipeline/base/node.py", line 115, in fit_traverse
    node.fit_output = node.fit(**required_kwargs)
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/pipeline/nodes/image/single_dataset.py", line 21, in fit
    budget=budget, budget_type=budget_type, config_id=config_id, working_directory=working_directory)
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/pipeline/base/pipeline.py", line 60, in fit_pipeline
    return self.root.fit_traverse(**kwargs)
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/pipeline/base/node.py", line 115, in fit_traverse
    node.fit_output = node.fit(**required_kwargs)
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/pipeline/nodes/image/cross_validation_indices.py", line 144, in fit
    working_directory=working_directory)
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/pipeline/base/pipeline.py", line 60, in fit_pipeline
    return self.root.fit_traverse(**kwargs)
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/pipeline/base/node.py", line 115, in fit_traverse
    node.fit_output = node.fit(**required_kwargs)
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/pipeline/nodes/image/simple_train_node.py", line 135, in fit
    optimize_metric_results, train_loss, stop_training = trainer.train(epoch + 1, train_loader, optimize_metrics)
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/components/training/image/trainer.py", line 85, in train
    outputs = self.model(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/components/networks/image/densenet.py", line 127, in forward
    features = self.features(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [80, 1, 3, 3], expected input[131, 3, 28, 28] to have 1 channels, but got 3 channels instead
20:06:27 job (1, 0, 0) failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/core/worker_no_timelimit.py", line 69, in compute
    raise Exception("Exception in train pipeline. Took " + str((time.time()-start_time)) + " seconds with budget " + str(budget))
Exception: Exception in train pipeline. Took 13.866185426712036 seconds with budget 400.0

**Comment by mens-artis** [comment]
with this cs:
networks=[resnet, mobilenet]
batch_loss_computation_techniques=[standard, mixup]
optimizer=[adamw, sgd]

it runs, although another bug exists:

0 60000
/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:156: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
09:59:33 job (0, 0, 0) failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/content/drive/MyDrive/Auto-PyTorch-master/autoPyTorch/core/worker_no_timelimit.py", line 74, in compute
    random.setstate(randomstate)
UnboundLocalError: local variable 'randomstate' referenced before assignment
